Importing libraries

In [26]:
# Warning : the backend below may generate some issues if used
# in a conda environment.
%matplotlib tk
# Try this backend if %matplotlib tk does not work properly
# In this case do not use the ginput command.
#%matplotlib notebook
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
from scipy import linalg

import warnings

def fxn():
    warnings.warn("deprecated", DeprecationWarning)

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    fxn()

Enter dimensions of soccer field

In [25]:
goal_width=7.32
goal_height=2.44
goal_area_1=5.5
goal_area_2=18.32
penalty_area_1=16.5
penalty_area_2=40.32
corner_arc=1
flag_height=1.5
field_1=65
field_2=105

Enter 3D point coordinates - Goal-> Goal area -> Penalty area -> Corners -> Corner radius points -> Flag extremity

In [28]:
        # Goal
u_field=np.array([[goal_width/2,0,0],[goal_width/2,goal_height,0],   
        [-goal_width/2,goal_height,0],[-goal_width/2,0,0],            
        # Goal
        [goal_area_2/2,0,0],[goal_area_2/2,0,goal_area_1],           
        # Goal area
        [-goal_area_2/2,0,goal_area_1],[-goal_area_2/2,0,0],
        # Goal area
        [penalty_area_2/2,0,0],[penalty_area_2/2,0,penalty_area_1],
        # Penalty area
        [-penalty_area_2/2,0,penalty_area_1],[-penalty_area_2/2,0,0],
        # Penalty area
        [field_1/2,0,0],[-field_1/2,0,0], # Corners
        [field_1/2-corner_arc,0,0],[-field_1/2+corner_arc,0,0],
        # Corner radius x
        [field_1/2,0,corner_arc],[-field_1/2,0,corner_arc],
        # Corner radius y
        [field_1/2,flag_height,0],[-field_1/2,flag_height,0]])
        # Flag extremities

Keep points that are visible in the image buffer

In [27]:
    # Goal
u_w=np.array([[goal_width/2,0,0],[goal_width/2,goal_height,0],
    # Goal
    [-goal_width/2,goal_height,0],[-goal_width/2,0,0],
    # Goal area
    [goal_area_2/2,0,0],[goal_area_2/2,0,goal_area_1],
    # Goal area
    [-goal_area_2/2,0,goal_area_1],[-goal_area_2/2,0,0],
    # Penalty area
    [-penalty_area_2/2,0,0],
    # Corners
    [-field_1/2,0,0],
    # Corner radius x
    [-field_1/2+corner_arc,0,0],
    # Corner radius y
    [-field_1/2,0,corner_arc],
    # Flag extremities
    [-field_1/2,flag_height,0]])          

# Number of visible points
N=np.shape(u_w)[0]
# Transformation to homogeneous coordinates
u_w= np.vstack((np.transpose(u_w),np.ones(N)))

Show 3D cloud of points

In [29]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(u_w[0,:],-u_w[2,:],u_w[1,:])
ax.set_xlim(-35, 35)
ax.set_zlim(-10, 1)
ax.set_ylim(-2,10)
plt.show()

Get image buffer points manually

In [30]:
img=mpimg.imread('goal.jpg')
fig,ax = plt.subplots()
ax.imshow(img)

# If %matplotlib works properly you can
# use the following two lines
# Image buffer points from mouse clicks
u_im = np.array(plt.ginput(N,timeout=-1))
plt.close()

# If you %matplotlib does not work properly
# you can try the code below
#u_im= np.array([]).reshape(0,2)
#def onclick(event):
#    global ix, iy
#    ix, iy = event.xdata, event.ydata
    
#    global u_im
#    u_im = np.vstack((u_im,np.array([[ix,iy]])))

#    if np.shape(u_im)[0] == 13:
#        fig.canvas.mpl_disconnect(cid)
#        plt.close()
        
#cid = fig.canvas.mpl_connect('button_press_event', onclick)

In [31]:
print(u_im)

[[1669.875       980.20040323]
 [1685.27016129  610.71653226]
 [1431.25        414.42822581]
 [1423.55241935  753.12177419]
 [1870.01209677 1191.88387097]
 [ 961.69758065 1211.12782258]
 [ 565.27217742  633.80927419]
 [1277.2983871   626.11169355]
 [1030.97580645  395.18427419]
 [ 796.19959677  168.10564516]
 [ 815.44354839  183.50080645]
 [ 715.375       171.95443548]
 [ 803.89717742   18.00282258]]


Show image point coordinates in homogeneous coordinates

In [32]:
u_im = np.vstack((np.transpose(u_im),np.ones(N)))
print(u_im)

[[1.66987500e+03 1.68527016e+03 1.43125000e+03 1.42355242e+03
  1.87001210e+03 9.61697581e+02 5.65272177e+02 1.27729839e+03
  1.03097581e+03 7.96199597e+02 8.15443548e+02 7.15375000e+02
  8.03897177e+02]
 [9.80200403e+02 6.10716532e+02 4.14428226e+02 7.53121774e+02
  1.19188387e+03 1.21112782e+03 6.33809274e+02 6.26111694e+02
  3.95184274e+02 1.68105645e+02 1.83500806e+02 1.71954435e+02
  1.80028226e+01]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00]]


Show chosen points

In [33]:
# Change backend if necessary
#%matplotlib inline

In [34]:
fig,ax = plt.subplots()
ax.imshow(img)
plt.scatter(u_im[0,:],u_im[1,:])
plt.show()

Centering and scaling

3D points

In [35]:
s_w    =1./(np.std(u_w,1,keepdims=True)[0:3])# Scaling
t_w    =-(np.mean(u_w,1,keepdims=True)[0:3]) # Translation
diag_s =np.diag(np.squeeze(s_w))
# Stacking scaling and translation
T_w    =np.array(np.hstack((diag_s,t_w*s_w)))
T_w    =np.vstack((T_w,np.array([0,0,0,1])))
print(T_w)

[[ 0.06329239  0.          0.          0.72620717]
 [ 0.          1.08582757  0.         -0.53289076]
 [ 0.          0.          0.50775827 -0.46869994]
 [ 0.          0.          0.          1.        ]]


Image buffer points

In [36]:
s_im   =1./(np.std(u_im,1,keepdims=True)[0:2]) # Scaling
t_im   =-(np.mean(u_im,1,keepdims=True)[0:2])  # Translation
diag_s =np.diag(np.squeeze(s_im))
# Stacking scaling and translation
T_im   =np.array(np.hstack((diag_s,t_im*s_im)))
T_im   =np.vstack((T_im,np.array([0,0,1])))
print(T_im)

[[ 2.44089700e-03  0.00000000e+00 -2.82507896e+00]
 [ 0.00000000e+00  2.66017483e-03 -1.50568916e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


Transformed 3D points and buffer points

In [37]:
u_w_t = np.dot(T_w,u_w)   # Transformed 3D points
u_im_t= np.dot(T_im,u_im) # Transformed image buffer points

Construction of the A matrix for DLT

In [38]:
u_w_i=np.transpose(u_w_t[:,0].reshape(-1,1))
A_i_1=np.hstack((np.zeros((1,4)),-u_w_i,u_im_t[1,0]*u_w_i))
A_i_2=np.hstack((u_w_i,np.zeros((1,4)),-u_im_t[0,0]*u_w_i))
A    = np.vstack((A_i_1,A_i_2))
# Stacking matrices for each point correspondence
for i in range(1,N):    
    u_w_i=np.transpose(u_w_t[:,i].reshape(-1,1))
    A_i_1=np.hstack((np.zeros((1,4)),-u_w_i,u_im_t[1,i]*u_w_i))
    A_i_2=np.hstack((u_w_i,np.zeros((1,4)),-u_im_t[0,i]*u_w_i))
    A    = np.vstack((A,A_i_1,A_i_2))

Solution using the SVD

In [39]:
U,S,V = np.linalg.svd(A) # SVD
m_t   = V[11,:]          # Last row of V, 
                         # since python's V is the transpose
                         # of the SVD's V 
print(m_t)

[-5.00980561e-01 -2.22495417e-03  3.32792886e-01  7.41908006e-02
 -5.33993328e-01  1.71686895e-01 -8.20852640e-03  9.09065475e-02
  9.96477565e-02  3.46144200e-03  3.62840161e-05 -5.47594599e-01]


Reshape to get M_t

In [40]:
M_t   = m_t.reshape(3,4)
print(M_t)

[[-5.00980561e-01 -2.22495417e-03  3.32792886e-01  7.41908006e-02]
 [-5.33993328e-01  1.71686895e-01 -8.20852640e-03  9.09065475e-02]
 [ 9.96477565e-02  3.46144200e-03  3.62840161e-05 -5.47594599e-01]]


Transform to get M

In [41]:
M = np.dot(np.linalg.inv(T_im),np.dot(M_t,T_w))

Rescale to get three first elements of third row with unitary norm

In [42]:
M = -M/np.linalg.norm(M[2,0:3])
print(M)

[[ 7.75105077e+02 -4.57688480e+02 -9.43198467e+03  1.00007920e+05]
 [ 1.24425433e+03 -9.83474721e+03  2.11982317e+02  5.64683123e+04]
 [-8.59026949e-01 -5.11924218e-01 -2.50934346e-03  6.49814223e+01]]


Getting Intrinsic and rotation matrices with RQ decomposition

In [43]:
M_int, R = linalg.rq(M[:,0:3])
print(M_int)
print(R)

[[ 9.44951596e+03  5.59369884e+02 -4.07866243e+02]
 [ 0.00000000e+00  9.08801568e+03  3.96526533e+03]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 0.01465641 -0.01969366 -0.99969863]
 [ 0.51172052 -0.85880484  0.02442035]
 [-0.85902695 -0.51192422 -0.00250934]]


Change signs of columns of M_int
and corresponding rows of R if necessary

In [44]:
#M_int[:,0] = -M_int[:,0]
#R[0,:] = -R[0,:]
#M_int[:,1] = -M_int[:,1]
#R[1,:] = -R[1,:]
#M_int[:,2] = -M_int[:,2]
#R[2,:] = -R[2,:]
print(M_int)
print(R)

[[ 9.44951596e+03  5.59369884e+02 -4.07866243e+02]
 [ 0.00000000e+00  9.08801568e+03  3.96526533e+03]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 0.01465641 -0.01969366 -0.99969863]
 [ 0.51172052 -0.85880484  0.02442035]
 [-0.85902695 -0.51192422 -0.00250934]]


Checking determinant of the rotation matrix

In [45]:
print(np.linalg.det(R))

1.0000000000000002


Project points on the image buffer using the estimated camera matrix

In [46]:
u_sim=np.dot(M,u_w)
u_sim=u_sim/u_sim[2,:]

fig,ax = plt.subplots()
ax.imshow(img)
plt.scatter(u_sim[0,:],u_sim[1,:])
plt.show()

Evaluate translation vector

In [47]:
t=np.linalg.solve(M_int,M[:,3])
print(-np.dot(R.T,t))

[66.93438232 14.54188933 15.39797289]
